# Site settings
name: Jack Ivanov
email: jack@ivlis.dev
#canonical_url: https://edwinexemplar.com
keywords: "DevOps, Software Engineer, Python, Go, DevOps, Startups, Agile"
skills: "Skilled DevOps with experience at networking and programming, belief to infrastructure as code, working remotelly and seeking for an opportunity to be useful and leverage existing skills to drive the projects into an 'automate everything' approach"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: github
    url: https://github.com/jackivanov
  - title: address-card
    url: https://www.upwork.com/fl/dev0ps
  - title: linkedin
    url: https://www.linkedin.com/in/dev0ps/

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
